Optima_Anbar/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Optima_Anbar.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        public double Quantity { get; set; }

        public double SalePrice { get; set; }

        public double BuyingPrice { get; set; }

        public DateTime AddingDate { get; set; }

        public double Profit { get; set; }
    }
}

Optima_Anbar/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Optima_Anbar.Data;
using Optima_Anbar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Optima_Anbar.Controllers
{
    public class ProductController : Controller
    {

        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin, Moderator")]
        public IActionResult Index()
        {
            List<Product> model = _context.Products.ToList();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Product model)
        {
            if (ModelState.IsValid)
            {
                model.AddingDate = DateTime.Now;
                model.Profit = model.Quantity * (model.SalePrice - model.BuyingPrice);              
                _context.Products.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "ERROR");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id)
        {
            return View(_context.Products.Find(id));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(Product model)
        {
            if (ModelState.IsValid)
            {
                model.Profit = model.Quantity * (model.SalePrice - model.BuyingPrice);
                _context.Products.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Error");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {

            Product product = _context.Products.Find(id);

            _context.Products.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Optima_Anbar/Views/Product/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <form asp-controller="Product" asp-action="Create" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Adı</label>
                    <input class="form-control" asp-for="@Model.Name">
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.Quantity" class="form-label">Miqdarı</label>
                    <input class="form-control" asp-for="@Model.Quantity">
                    <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.SalePrice" class="form-label">Satış Qiyməti</label>
                    <input class="form-control" asp-for="@Model.SalePrice">
                    <span asp-validation-for="@Model.SalePrice" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.BuyingPrice" class="form-label">Alış Qiyməti</label>
                    <input class="form-control" asp-for="@Model.BuyingPrice">
                    <span asp-validation-for="@Model.BuyingPrice" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-controller="Product" asp-action="Index">Back to list</a>
            </form>
        </div>
    </div>
</div>

Optima_Anbar/Views/Product/Index.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary mb-3" asp-controller="Product" asp-action="Create">Yeni Məhsul Əlavə et</a>
        </div>
        <hr />

        <div class="col-lg-12 mt-3">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Adı</th>
                        <th scope="col">Miqdarı</th>
                        <th scope="col">Satış Qiyməti</th>
                        <th scope="col">Maya Dəyəri</th>
                        <th scope="col">Qazanc</th>
                        <th scope="col">Əlavə edilmə tarixi </th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{ int i = 0;
                        foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <th scope="row">@i</th>
                                <td>@item.Name</td>
                                <td>@item.Quantity</td>
                                <td>@item.SalePrice</td>
                                <td>@item.BuyingPrice</td>
                                <td>@item.Profit</td>
                                <td>@item.AddingDate</td>
                                <td>
                                    <a class="btn btn-success" asp-controller="Product" asp-action="Update" asp-route-id="@item.Id">Düzəliş</a>
                                    <a class="btn btn-danger" asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure?')">Sil</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

Optima_Anbar/Views/Product/Update.cshtml
@model Product
@{
    ViewData["Title"] = "Update";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <form asp-controller="Product" asp-action="Update" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Adı</label>
                    <input class="form-control" asp-for="@Model.Name">
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.Quantity" class="form-label">Miqdarı</label>
                    <input class="form-control" asp-for="@Model.Quantity">
                    <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.SalePrice" class="form-label">Satış Qiyməti</label>
                    <input class="form-control" asp-for="@Model.SalePrice">
                    <span asp-validation-for="@Model.SalePrice" class="text-danger"></span>
                </div>
                <div class="mb-3 col-3">
                    <label asp-for="@Model.BuyingPrice" class="form-label">Alış Qiyməti</label>
                    <input class="form-control" asp-for="@Model.BuyingPrice">
                    <span asp-validation-for="@Model.BuyingPrice" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="@Model.AddingDate" value="@Model.AddingDate">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-controller="Product" asp-action="Index">Back to list</a>
            </form>
        </div>
    </div>
</div>